id: A85C49CC0
title: Prayer for the Long Life of Alak Zenkar Rinpoche
type: translation
pechas:
- I5ED0CECE
- IBE11BEA9
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:28:51.899752
  last_modified_at: 2023-01-04 11:28:51.899765
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I5ED0CECE/76E6: D707
  IBE11BEA9/8A25: D707
